### ISSUE TITLE
关闭设置窗口会导致GNOME崩溃

### ISSUE THREAD

**Issue by 3406819948** [yt-theme/popBall#10]
**Describe the bug**
如题

**To Reproduce**
1. 右键
2. 点击configure
3. 关闭设置窗口
4. GNOME崩溃重启

**Desktop (please complete the following information):**
 - OS: debian 10
 - GNOME: 3.30

**Additional context**
因为我用的GNOME版本比较老，所以我不确定最新版GNOME是不是也存在这个问题，如果是，下面有一个比较笨的解决办法：
> void Widget::setting_panel () {
  hide();
  setWindowFlags(windowFlags() & ~Qt::BypassWindowManagerHint);
  QDialog *dialog = new ConfigureDialog(this);
  ...
  dialog->exec();
  setWindowFlags(windowFlags() | Qt::BypassWindowManagerHint);
  show();
}

**Comment by yt-theme** [comment]
> **Describe the bug**
> 如题
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. 右键
> 2. 点击configure
> 3. 关闭设置窗口
> 4. GNOME崩溃重启
> 
> **Desktop (please complete the following information):**
> 
> * OS: debian 10
> * GNOME: 3.30
> 
> **Additional context**
> 因为我用的GNOME版本比较老，所以我不确定最新版GNOME是不是也存在这个问题，如果是，下面有一个比较笨的解决办法：
> 
> > void Widget::setting_panel () {
> > hide();
> > setWindowFlags(windowFlags() & ~Qt::BypassWindowManagerHint);
> > QDialog *dialog = new ConfigureDialog(this);
> > ...
> > dialog->exec();
> > setWindowFlags(windowFlags() | Qt::BypassWindowManagerHint);
> > show();
> > }

大佬窝不知道为啥这样做能消除bug求教

**Comment by 3406819948** [comment]
感兴趣的话可以看看这个
[https://gitlab.gnome.org/GNOME/mutter/merge_requests/895](https://gitlab.gnome.org/GNOME/mutter/merge_requests/895)

Qt::BypassWindowManagerHint对应的是X窗口的override_redirect属性，窗口管理器会忽略设置了这个属性的窗口，当它不存在。如果把父窗口设置成这种“不存在”的窗口，那么在关闭子窗口的时侯，窗口管理器就会试着把焦点转移到一个“不存在”的窗口，于是问题出现了。

据说GNOME 3.34.2已经解决了，而且我用的是X，Wayland应该没事？

**Comment by yt-theme** [comment]
> 感兴趣的话可以看看这个
> https://gitlab.gnome.org/GNOME/mutter/merge_requests/895
> 
> Qt::BypassWindowManagerHint对应的是X窗口的override_redirect属性，窗口管理器会忽略设置了这个属性的窗口，当它不存在。如果把父窗口设置成这种“不存在”的窗口，那么在关闭子窗口的时侯，窗口管理器就会试着把焦点转移到一个“不存在”的窗口，于是问题出现了。
> 
> 据说GNOME 3.34.2已经解决了，而且我用的是X，Wayland应该没事？

大佬吼腻害

**Comment by 3406819948** [comment]
我来填坑了，Widget::main_ui_style这三行的前面两行好像没起作用
`this->setWindowFlag(Qt::FramelessWindowHint);`
`this->setWindowFlag(Qt::Tool);`
`this->setWindowFlag(Qt::WindowStaysOnTopHint); `
改成 `this->setWindowFlags(Qt::FramelessWindowHint | Qt::Tool | Qt::WindowStaysOnTopHint);`，
然后下面的`this->setWindowFlags(windowFlags()|Qt::BypassWindowManagerHint);`就变得不重要了吧，FramelessWindowHint的效果和BypassWindowManagerHint应该是一样的，把这行删掉就可以彻底搞定GNOME 3.30 on Xorg的崩溃问题。浮动球挺好玩的，感谢大佬分享。
