### ISSUE TITLE
发个release,我好打包

### ISSUE THREAD

**Issue by CoelacanthusHex** [yt-theme/popBall#4]
发个release,我好打包
打包的事就在这里讨论吧

**Comment by CoelacanthusHex** [comment]
你传还是我传

**Comment by CoelacanthusHex** [comment]
我把git版本的传了

**Comment by CoelacanthusHex** [comment]
你用户名多少,我加一下共同维护者

**Comment by CoelacanthusHex** [comment]
合一下PR

**Comment by yt-theme** [comment]
吼惹

**Comment by yt-theme** [comment]
是登录名么13133528465@163.com

**Comment by yt-theme** [comment]
已合并

**Comment by CoelacanthusHex** [comment]
> 是登录名么[13133528465@163.com](mailto:13133528465@163.com)

是

**Comment by CoelacanthusHex** [comment]
好惹,咱把ICON更新上了,

**Comment by yt-theme** [comment]
> 好惹,咱把ICON更新上了,

窝装上试

**Comment by yt-theme** [comment]
> 好惹,咱把ICON更新上了,

装上报了个错误不知道怎么解决了呢
Cloning into 'yt-popball'...
done.
==> Starting prepare()...
==> Starting pkgver()...
fatal: No annotated tags can describe '238890f4f858edfe02cd518767aeec338410d71e'.
However, there were unannotated tags: try --tags.
==> ERROR: pkgver is not allowed to be empty.
==> ERROR: pkgver() generated an invalid version: 
Error making: yt-popball-git

**Comment by CoelacanthusHex** [comment]
> > 好惹,咱把ICON更新上了,
> 
> 装上报了个错误不知道怎么解决了呢
> Cloning into 'yt-popball'...
> done.
> ==> Starting prepare()...
> ==> Starting pkgver()...
> fatal: No annotated tags can describe '238890f4f858edfe02cd518767aeec338410d71e'.
> However, there were unannotated tags: try --tags.
> ==> ERROR: pkgver is not allowed to be empty.
> ==> ERROR: pkgver() generated an invalid version:
> Error making: yt-popball-git

我去看看

**Comment by CoelacanthusHex** [comment]
> > 好惹,咱把ICON更新上了,
> 
> 装上报了个错误不知道怎么解决了呢
> Cloning into 'yt-popball'...
> done.
> ==> Starting prepare()...
> ==> Starting pkgver()...
> fatal: No annotated tags can describe '238890f4f858edfe02cd518767aeec338410d71e'.
> However, there were unannotated tags: try --tags.
> ==> ERROR: pkgver is not allowed to be empty.
> ==> ERROR: pkgver() generated an invalid version:
> Error making: yt-popball-git

你发个tag位0.1的release试试

**Comment by yt-theme** [comment]
> > > 好惹,咱把ICON更新上了,
> > 
> > 
> > 装上报了个错误不知道怎么解决了呢
> > Cloning into 'yt-popball'...
> > done.
> > ==> Starting prepare()...
> > ==> Starting pkgver()...
> > fatal: No annotated tags can describe '238890f4f858edfe02cd518767aeec338410d71e'.
> > However, there were unannotated tags: try --tags.
> > ==> ERROR: pkgver is not allowed to be empty.
> > ==> ERROR: pkgver() generated an invalid version:
> > Error making: yt-popball-git
> 
> 你发个tag位0.1的release试试

发惹

**Comment by CoelacanthusHex** [comment]
修好惹

**Comment by CoelacanthusHex** [comment]
> 是登录名么[13133528465@163.com](mailto:13133528465@163.com)

你的用户名是邮箱?

**Comment by yt-theme** [comment]
> > 是登录名么[13133528465@163.com](mailto:13133528465@163.com)
> 
> 你的用户名是邮箱?

是的 但不是现在的手机号 这个手机号早就不用惹
还有窝想到贴吧宣传一下 分享给更多用户

**Comment by yt-theme** [comment]
> > 是登录名么[13133528465@163.com](mailto:13133528465@163.com)
> 
> 你的用户名是邮箱?

另外
大佬
吼腻害

**Comment by CoelacanthusHex** [comment]
> > > 是登录名么[13133528465@163.com](mailto:13133528465@163.com)
> > 
> > 
> > 你的用户名是邮箱?
> 
> 另外
> 大佬
> 吼腻

非法用户名：13133528465@163.com

**Comment by yt-theme** [comment]
> > > > 是登录名么[13133528465@163.com](mailto:13133528465@163.com)
> > > 
> > > 
> > > 你的用户名是邮箱?
> > 
> > 
> > 另外
> > 大佬
> > 吼腻
> 
> 非法用户名：[13133528465@163.com](mailto:13133528465@163.com)

chinux_2012呢

**Comment by CoelacanthusHex** [comment]
emmm

**Comment by yt-theme** [comment]
> emmm

还是不对么

**Comment by CoelacanthusHex** [comment]
> > emmm
> 
> 还是不对么

加好惹,我多摁了个空格

**Comment by yt-theme** [comment]
> > > emmm
> > 
> > 
> > 还是不对么
> 
> 加好惹,我多摁了个空格

乖要不加qq群窝萌一起搞事情644125955

**Comment by CoelacanthusHex** [comment]
> > > > emmm
> > > 
> > > 
> > > 还是不对么
> > 
> > 
> > 加好惹,我多摁了个空格
> 
> 乖要不加qq群窝萌一起搞事情644125955

好
