### ISSUE TITLE
[Feature Request]希望添加初始生成位置

### ISSUE THREAD

**Issue by CoelacanthusHex** [yt-theme/popBall#7]
希望添加初始生成位置

**Comment by yt-theme** [comment]
具体有啥功能 配置文件么

**Comment by yt-theme** [comment]
> 希望添加初始生成位置

记录上次窗口的位置

**Comment by CoelacanthusHex** [comment]
> > 希望添加初始生成位置
> 
> 记录上次窗口的位置

这个主意不错

**Comment by yt-theme** [comment]
> > > 希望添加初始生成位置
> > 
> > 
> > 记录上次窗口的位置
> 
> 这个主意不错

加吼惹 要不有时间多测试一下

**Comment by yt-theme** [comment]
> > > 希望添加初始生成位置
> > 
> > 
> > 记录上次窗口的位置
> 
> 这个主意不错

默认位置(0, 0)
