### ISSUE TITLE
[Bug]可能会吧悬浮球拖出屏幕

### ISSUE THREAD

**Issue by CoelacanthusHex** [yt-theme/popBall#9]
**Describe the bug**

可能会吧悬浮球拖出屏幕

**To Reproduce**

你按着悬浮球边缘往屏幕边缘拖

**Expected behavior**

倒边缘会自动停下

**Desktop (please complete the following information):**
 - OS: Arch KDE

**Comment by yt-theme** [comment]
> **Describe the bug**
> 
> 可能会吧悬浮球拖出屏幕
> 
> **To Reproduce**
> 
> 你按着悬浮球边缘往屏幕边缘拖
> 
> **Expected behavior**
> 
> 倒边缘会自动停下
> 
> **Desktop (please complete the following information):**
> 
> * OS: Arch KDE

改成拖到屏幕边缘自动变成吸附到边缘不太占地方的那种外观 只显示很小的两个柱状图那种

**Comment by yt-theme** [comment]
> **Describe the bug**
> 
> 可能会吧悬浮球拖出屏幕
> 
> **To Reproduce**
> 
> 你按着悬浮球边缘往屏幕边缘拖
> 
> **Expected behavior**
> 
> 倒边缘会自动停下
> 
> **Desktop (please complete the following information):**
> 
> * OS: Arch KDE

mini mode is complete

**Comment by yt-theme** [comment]
> **Describe the bug**
> 
> 可能会吧悬浮球拖出屏幕
> 
> **To Reproduce**
> 
> 你按着悬浮球边缘往屏幕边缘拖
> 
> **Expected behavior**
> 
> 倒边缘会自动停下
> 
> **Desktop (please complete the following information):**
> 
> * OS: Arch KDE

要不整个包呦呦

**Comment by CoelacanthusHex** [comment]
> > **Describe the bug**
> > 可能会吧悬浮球拖出屏幕
> > **To Reproduce**
> > 你按着悬浮球边缘往屏幕边缘拖
> > **Expected behavior**
> > 倒边缘会自动停下
> > **Desktop (please complete the following information):**
> > 
> > * OS: Arch KDE
> 
> 要不整个包呦呦

包已更新
